spring:
  application:
    name: School-Management Project
  datasource:
    url: jdbc:mysql://localhost:3306/school?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8082